export const salesData = [
    { productName: 'Product A', category: 'Electronics', quantitySold: 15, salesAmount: 300 },
    { productName: 'Product B', category: 'Electronics', quantitySold: 7, salesAmount: 140 },
    { productName: 'Product C', category: 'Furniture', quantitySold: 10, salesAmount: 500 },
    { productName: 'Product D', category: 'Furniture', quantitySold: 12, salesAmount: 600 },
    { productName: 'Product E', category: 'Clothing', quantitySold: 20, salesAmount: 200 },
    { productName: 'Product F', category: 'Clothing', quantitySold: 25, salesAmount: 250 },
    { productName: 'Product G', category: 'Books', quantitySold: 30, salesAmount: 300 },
    { productName: 'Product H', category: 'Books', quantitySold: 22, salesAmount: 220 },
    { productName: 'Product I', category: 'Toys', quantitySold: 18, salesAmount: 360 },
    { productName: 'Product J', category: 'Toys', quantitySold: 14, salesAmount: 280 },
    { productName: 'Product K', category: 'Health', quantitySold: 9, salesAmount: 270 },
    { productName: 'Product L', category: 'Health', quantitySold: 13, salesAmount: 390 },
    { productName: 'Product M', category: 'Sports', quantitySold: 11, salesAmount: 220 },
    { productName: 'Product N', category: 'Sports', quantitySold: 8, salesAmount: 160 },
    { productName: 'Product O', category: 'Automotive', quantitySold: 5, salesAmount: 500 },
    { productName: 'Product P', category: 'Automotive', quantitySold: 6, salesAmount: 600 },
    { productName: 'Product Q', category: 'Beauty', quantitySold: 17, salesAmount: 340 },
    { productName: 'Product R', category: 'Beauty', quantitySold: 19, salesAmount: 380 },
    { productName: 'Product S', category: 'Jewelry', quantitySold: 4, salesAmount: 800 },
    { productName: 'Product T', category: 'Jewelry', quantitySold: 3, salesAmount: 600 },
    { productName: 'Product U', category: 'Garden', quantitySold: 13, salesAmount: 390 },
    { productName: 'Product V', category: 'Garden', quantitySold: 11, salesAmount: 330 },
    { productName: 'Product W', category: 'Office Supplies', quantitySold: 25, salesAmount: 125 },
    { productName: 'Product X', category: 'Office Supplies', quantitySold: 22, salesAmount: 110 },
    { productName: 'Product Y', category: 'Pet Supplies', quantitySold: 9, salesAmount: 180 },
    { productName: 'Product Z', category: 'Pet Supplies', quantitySold: 8, salesAmount: 160 },
];

export const salesComparisonData = [
    { productName: 'Product A', category: 'Electronics', date1SalesAmount: 300, date2SalesAmount: 350, difference: 50 },
    { productName: 'Product B', category: 'Electronics', date1SalesAmount: 140, date2SalesAmount: 160, difference: 20 },
    { productName: 'Product C', category: 'Furniture', date1SalesAmount: 500, date2SalesAmount: 550, difference: 50 },
    { productName: 'Product D', category: 'Furniture', date1SalesAmount: 600, date2SalesAmount: 700, difference: 100 },
    { productName: 'Product E', category: 'Clothing', date1SalesAmount: 200, date2SalesAmount: 180, difference: -20 },
    { productName: 'Product F', category: 'Clothing', date1SalesAmount: 250, date2SalesAmount: 270, difference: 20 },
    { productName: 'Product G', category: 'Books', date1SalesAmount: 300, date2SalesAmount: 320, difference: 20 },
    { productName: 'Product H', category: 'Books', date1SalesAmount: 220, date2SalesAmount: 250, difference: 30 },
    { productName: 'Product I', category: 'Toys', date1SalesAmount: 360, date2SalesAmount: 340, difference: -20 },
    { productName: 'Product J', category: 'Toys', date1SalesAmount: 280, date2SalesAmount: 290, difference: 10 },
    { productName: 'Product K', category: 'Health', date1SalesAmount: 270, date2SalesAmount: 300, difference: 30 },
    { productName: 'Product L', category: 'Health', date1SalesAmount: 390, date2SalesAmount: 400, difference: 10 },
    { productName: 'Product M', category: 'Sports', date1SalesAmount: 220, date2SalesAmount: 200, difference: -20 },
    { productName: 'Product N', category: 'Sports', date1SalesAmount: 160, date2SalesAmount: 180, difference: 20 },
    { productName: 'Product O', category: 'Automotive', date1SalesAmount: 500, date2SalesAmount: 600, difference: 100 },
    { productName: 'Product P', category: 'Automotive', date1SalesAmount: 600, date2SalesAmount: 650, difference: 50 },
    { productName: 'Product Q', category: 'Beauty', date1SalesAmount: 340, date2SalesAmount: 370, difference: 30 },
    { productName: 'Product R', category: 'Beauty', date1SalesAmount: 380, date2SalesAmount: 400, difference: 20 },
    { productName: 'Product S', category: 'Jewelry', date1SalesAmount: 800, date2SalesAmount: 850, difference: 50 },
    { productName: 'Product T', category: 'Jewelry', date1SalesAmount: 600, date2SalesAmount: 620, difference: 20 },
    { productName: 'Product U', category: 'Garden', date1SalesAmount: 390, date2SalesAmount: 400, difference: 10 },
    { productName: 'Product V', category: 'Garden', date1SalesAmount: 330, date2SalesAmount: 310, difference: -20 },
    { productName: 'Product W', category: 'Office Supplies', date1SalesAmount: 125, date2SalesAmount: 140, difference: 15 },
    { productName: 'Product X', category: 'Office Supplies', date1SalesAmount: 110, date2SalesAmount: 120, difference: 10 },
    { productName: 'Product Y', category: 'Pet Supplies', date1SalesAmount: 180, date2SalesAmount: 190, difference: 10 },
    { productName: 'Product Z', category: 'Pet Supplies', date1SalesAmount: 160, date2SalesAmount: 170, difference: 10 },
    { productName: 'Product AA', category: 'Electronics', date1SalesAmount: 280, date2SalesAmount: 290, difference: 10 },
    { productName: 'Product BB', category: 'Electronics', date1SalesAmount: 200, date2SalesAmount: 210, difference: 10 },
    { productName: 'Product CC', category: 'Furniture', date1SalesAmount: 700, date2SalesAmount: 720, difference: 20 },
    { productName: 'Product DD', category: 'Furniture', date1SalesAmount: 800, date2SalesAmount: 850, difference: 50 },
    { productName: 'Product EE', category: 'Clothing', date1SalesAmount: 250, date2SalesAmount: 230, difference: -20 },
    { productName: 'Product FF', category: 'Clothing', date1SalesAmount: 300, date2SalesAmount: 310, difference: 10 },
    { productName: 'Product GG', category: 'Books', date1SalesAmount: 320, date2SalesAmount: 330, difference: 10 },
    { productName: 'Product HH', category: 'Books', date1SalesAmount: 250, date2SalesAmount: 260, difference: 10 },
    { productName: 'Product II', category: 'Toys', date1SalesAmount: 350, date2SalesAmount: 340, difference: -10 },
    { productName: 'Product JJ', category: 'Toys', date1SalesAmount: 290, date2SalesAmount: 300, difference: 10 },
    { productName: 'Product KK', category: 'Health', date1SalesAmount: 300, date2SalesAmount: 310, difference: 10 },
    { productName: 'Product LL', category: 'Health', date1SalesAmount: 400, date2SalesAmount: 420, difference: 20 },
    { productName: 'Product MM', category: 'Sports', date1SalesAmount: 200, date2SalesAmount: 190, difference: -10 },
    { productName: 'Product NN', category: 'Sports', date1SalesAmount: 180, date2SalesAmount: 200, difference: 20 },
    { productName: 'Product OO', category: 'Automotive', date1SalesAmount: 600, date2SalesAmount: 620, difference: 20 },
    { productName: 'Product PP', category: 'Automotive', date1SalesAmount: 650, date2SalesAmount: 670, difference: 20 },
    { productName: 'Product QQ', category: 'Beauty', date1SalesAmount: 370, date2SalesAmount: 380, difference: 10 },
    { productName: 'Product RR', category: 'Beauty', date1SalesAmount: 400, date2SalesAmount: 410, difference: 10 },
    { productName: 'Product SS', category: 'Jewelry', date1SalesAmount: 850, date2SalesAmount: 870, difference: 20 },
    { productName: 'Product TT', category: 'Jewelry', date1SalesAmount: 620, date2SalesAmount: 630, difference: 10 },
    { productName: 'Product UU', category: 'Garden', date1SalesAmount: 400, date2SalesAmount: 410, difference: 10 },
    { productName: 'Product VV', category: 'Garden', date1SalesAmount: 310, date2SalesAmount: 320, difference: 10 },
    { productName: 'Product WW', category: 'Office Supplies', date1SalesAmount: 140, date2SalesAmount: 150, difference: 10 },
    { productName: 'Product XX', category: 'Office Supplies', date1SalesAmount: 120, date2SalesAmount: 130, difference: 10 },
    { productName: 'Product YY', category: 'Pet Supplies', date1SalesAmount: 190, date2SalesAmount: 200, difference: 10 },
    { productName: 'Product ZZ', category: 'Pet Supplies', date1SalesAmount: 170, date2SalesAmount: 180, difference: 10 },
];
